### ISSUE TITLE
 erreur 429 could not connect to openai

### ISSUE THREAD

**Issue by Guitoutoutou** [ad2969/obsidian-auto-anki#13]
Hi all'
I have this message :  erreur 429 could not connect to openai (insufficient_quota) You exceeded your current quota, please check your plan and billing details.

Have you any idea of the problem ?

Tks

Gui

**Comment by ad2969** [comment]
Hi @Guitoutoutou, this is a problem related to your OpenAI account. You've likely set a quota for your account's free plan, or have a usage quota that limits your use of the API. See the official openAI support thread [here](https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details).

**Comment by Guitoutoutou** [comment]
Tks for your response. I'm on personnal plan and have 0 usage API plan... It doesn't matter. Tks for your job
