### ISSUE TITLE
GPT3 Depreciation 

### ISSUE THREAD

**Issue by LysanderTron** [ad2969/obsidian-auto-anki#19]
![broken](https://github.com/ad2969/obsidian-auto-anki/assets/68231960/9736997f-29f9-4fa5-b6f8-74b5b71125e8)

**Comment by ad2969** [comment]
Updated in [v0.2.1](https://github.com/ad2969/obsidian-auto-anki/releases/tag/0.2.1). Thanks @LysanderTron for pointing this out!
