### ISSUE TITLE
Plugin not found in community plugin store

### ISSUE THREAD

**Issue by zeitchef** [ad2969/obsidian-auto-anki#5]
As the title suggests, I'm not able to find the plugin when searching in the community plugin section. I'm using Obsidian 1.3.4 with everything up-to-date.

**Comment by ad2969** [comment]
@zeitchef Thanks for the comment! The plugin hasn't been merged into the community plugin store! There are some changes I have to make and I have yet to test it on windows and linux platforms - but I intend to do that tomorrow! [here's](https://github.com/obsidianmd/obsidian-releases/pull/1954#issuecomment-1550111196) the original PR for updates on when it might merge into the community plugin store!

**Comment by ad2969** [comment]
@zeitchef The maintainers just merged this plugin! Feel free to test it and let me know if there's any requests! Thank you :)

**Comment by ad2969** [comment]
@zeitchef The maintainers just merged this plugin! Feel free to test it and let me know if there are any requests! Thank you :)
